# dev-time dependencies
# ensure they aren't pruned
required = [
  "github.com/jteeuwen/go-bindata/go-bindata",
  "github.com/golang/dep/cmd/dep",
  "github.com/golang/lint/golint",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
]

# prune out unused content from vendor
[prune]
  go-tests = true
  non-go = true
  unused-packages = true

# Don't prune helper scripts from code-generator
 [[prune.project]]
   name = "k8s.io/code-generator"
   unused-packages = false

[[override]]
  name = "github.com/jteeuwen/go-bindata"
  # latest, unlikely to change as go-bindata is no longer maintained
  revision = "6025e8de665b31fa74ab1a66f2cddd8c0abf887e"

[[override]]
  name = "github.com/golang/dep"
  version = "v0.5.0"


# normal constraints below

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
 name = "k8s.io/code-generator"
 branch = "master"

