title = "kind"
baseURL = "https://kind.sigs.k8s.io"
languageCode = "en-us"

# we use this to disable indexing for the non-production build
enableRobotsTXT = true

# this allows us to show the source commit in the footer
enableGitInfo = true

# syntax highlighting options
pygmentsCodeFences = true
pygmentsStyle = "tango"

# we don't use these currently
disableKinds = ["taxonomy", "taxonomyTerm"]

# enable hugo's menu system for the site, name the primary menu
sectionPagesMenu = "main"
# menu entries
[menu]
  [[menu.main]]
    identifier = "ome"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "user"
    name = "User Guide"
    title = "User Guide"
    weight = 2
  [[menu.main]]
    identifier = "design"
    name = "Design"
    title = "Design"
    url = "/docs/design/"
    weight = 5
  [[menu.main]]
    identifier = "devel"
    name = "Developer Guide"
    title = "Developer Guide"
    url = "/docs/devel/"
    weight = 6
